name: run

on:
  schedule:
    - cron: "0 7 * * *"
  push:
    branches:
      - "main"

jobs:
  Run:
    runs-on: ubuntu-latest
    steps:
      - name: Begin Check...
        uses: actions/checkout@v2

      - name: Use NodeJS 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Use cached nude_modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: nodeModules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            nodeModules-

      - name: install dependencies
        run: npm ci
        env:
          CI: true

      - name: delete output.txt
        run: rm -Rf output.txt

      - name: run
        run: npm start

      - uses: EndBug/add-and-commit@v7
        with:
          add: "output.txt"
          default_author: github_actions
          message: "chore(output): daily report"
